version: "3.9"

services:
  app:
    container_name: bluelephant-assistant-app
    build: .

    ports:
      - "8501:8501"

    volumes:
      - ./auth:/app/auth
      - ./services/credentials.json:/app/services/credentials.json:ro

    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/services/credentials.json

    restart: always